### ISSUE TITLE
请问一下，训练出来的模型结果怎么样？精度能达到多少啊？

### ISSUE THREAD

**Issue by 10183308** [papercatnku/AIChallenger-SceneDetection-mxnet#1]

**Comment by papercatnku** [comment]
仅用ai-challengner 提供的训练集随机初始化做训练，测试集上大概达到70%的top3，我没做过验证，但是使用预训练网络初始化做finetune应该能达到或接近目前竞赛最高水平。不过目前pretrained资源不太多可以在https://github.com/hujie-frank/SENet看看。
我做过用place365的训练的实验，一个周末跑了将近3个epoch时大概验证集上top-1到了32%, top3到了59%，没有足够资源跑完更多epoch了。如果GPU资源足够多，可以自己用place365做训练，FYI。
